// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Models;

namespace TelegramPizzaria.Migrations
{
    [DbContext(typeof(ContextDb))]
    [Migration("20200823201952_executandoPelaPrimeiraVez")]
    partial class executandoPelaPrimeiraVez
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7");

            modelBuilder.Entity("Models.Data.Combo", b =>
                {
                    b.Property<int>("ComboId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeCombo")
                        .HasColumnType("TEXT");

                    b.HasKey("ComboId");

                    b.ToTable("combos");
                });

            modelBuilder.Entity("Models.Data.Pizza", b =>
                {
                    b.Property<int>("PizzaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomePizza")
                        .HasColumnType("TEXT");

                    b.HasKey("PizzaId");

                    b.ToTable("pizzas");
                });
#pragma warning restore 612, 618
        }
    }
}
